#!/bin/bash

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

# Set secure permissions for the initramfs if we're configuring
# full-disk-encryption. The initramfs is re-generated later in the
# installation process so we only set the permissions snippet without
# regenerating the initramfs right now:
if [ "$(mount | grep $CHROOT" " | cut -c -16)" = "/dev/mapper/luks" ]; then
    echo "UMASK=0077" > $CHROOT/etc/initramfs-tools/conf.d/initramfs-permissions
fi

echo "Running bootloader-config..."
if [ -d /sys/firmware/efi/efivars ]; then
    echo " * Installing grub-efi (uefi)..."
    if [ "$(cat /sys/firmware/efi/fw_platform_size)" == "64" ]; then
        echo " * 64bit efi implementation detected - selecting grub-efi-amd64"
        DEBIAN_FRONTEND=noninteractive chroot $CHROOT apt-get -y install grub-efi-amd64 cryptsetup keyutils
    elif [ "$(cat /sys/firmware/efi/fw_platform_size)" == "32" ]; then
        echo " * 32bit efi implementation detected - selecting grub-efi-ia32"
        DEBIAN_FRONTEND=noninteractive chroot $CHROOT apt-get -y install grub-efi-ia32 cryptsetup keyutils
    fi
else
    echo " * install grub... (bios)"
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT apt-get -y install cryptsetup keyutils
    DEBIAN_FRONTEND=noninteractive chroot $CHROOT apt-get -y install grub-pc || true
fi
